version: '3'
services:
  top_api:
    image: ghcr.io/afanasievkirill/nestjs_example/nestjs_api_example:develop
    container_name: top_api
    restart: always
    user: node
    ports:
      - 3000:3000
    depends_on: mongo_top_api
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    image: mongo:4.4.4
    container_name: mongo_top_api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
